# Generated by Django 4.1.7 on 2023-03-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="kegiatan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_at", models.DateTimeField(auto_created=True)),
                ("created_at", models.DateTimeField(auto_created=True)),
                ("isi", models.CharField(max_length=255)),
                ("keterangan", models.BooleanField(default=False)),
                ("tanggal", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
