# Generated by Django 4.1.7 on 2023-03-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logactivity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kegiatan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="kegiatan",
            name="update_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
